version: '3'
services:
  nginx:
    image: 232490755822.dkr.ecr.us-west-2.amazonaws.com/davidgiffin/aws-ecr-http-proxy:latest
    command: 
      - "/usr/bin/supervisord"
      - "-c"
      - "/etc/supervisord.conf"
    ports:
      - "5000:5000"
    environment:
      - AWS_REGION=us-west-2
      - AWS_ACCESS_KEY_ID=XXX
      - AWS_SECRET_ACCESS_KEY=XXX
      - UPSTREAM=https://XXX.dkr.ecr.us-west-2.amazonaws.com
      - RESOLVER=8.8.8.8
      - PORT=5000
